# Generated by Django 3.2.13 on 2022-07-28 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgmi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
