# Generated by Django 3.2.13 on 2022-07-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0002_bgmi_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgmi',
            name='created_at',
        ),
    ]
