# Generated by Django 3.2.13 on 2022-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0003_bgmi_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmi',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
