# Generated by Django 3.2.13 on 2022-07-30 15:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0003_remove_bgmi_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgmi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bgmi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
