# Generated by Django 3.2.13 on 2022-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0004_auto_20220730_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
