# Generated by Django 3.2.13 on 2022-07-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0005_alter_bgmi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgmi',
            name='price',
        ),
    ]
