# Generated by Django 3.2.13 on 2022-07-30 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0006_remove_bgmi_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgmi',
            name='price',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
