# Generated by Django 3.2.13 on 2022-07-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0007_bgmi_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmi',
            name='price',
            field=models.DateTimeField(),
        ),
    ]
