# Generated by Django 3.2.13 on 2022-07-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytourneys', '0009_alter_bgmi_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgmi',
            name='price',
        ),
    ]
